###
POST http://localhost:3000/stream HTTP/1.1
content-type: application/json

{
    "question":"hello",
    "history": ["hello"],
    "chatMode": "internet",
    "option2": "IB",
    "option3": "LV",
    "option4": "FORM"
}

###
GET http://localhost:3000 HTTP/1.1

###
GET https://fiscal-chat-server.onrender.com/ HTTP/1.1